### ISSUE TITLE
Add Author model and connect to Magazine Article

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#21]
Magazine Articles have one or more authors. The authors will have a first and last name.

## Task
- [x] Add `Author` model (or perhaps `Person`).
- [x] Add `slug` field to Author model
- [x] `Author` model fields should include first and last name.
- [x] Add `authored_by` relationship to Magazine Article model (many-to-many).
- [x] Display authors on Magazine Article
- [x] Add convenient UI for inline selection (and possibly creation) of Author from Article edit page
- [x] Magazine Author page should show name and related articles.
- [x] Magazine Author page should use `slug` in URL
