### ISSUE TITLE
Create custom `FormattedImage` allowing editor to select image size (and perhaps alignment)

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#303]
The default Wagtail image block only lets the content editor select the image and displays it in the full size rendition in the content (e.g., MagazineArticle). It would be useful for the editor to be able to select an image format when adding an article via a StreamField.

## Task

- [ ] create a `FormattedImage` block (or some similar name) that inherits from `StructBlock`
- [ ] add an image field to the block
- [ ] add a `format` field that lets the editor input the desired image width (in pixels)
- [ ] create the template to render the image with the [desired image format](https://docs.wagtail.io/en/stable/topics/images.html#how-to-use-images-in-templates)
- [x] use the `FormattedImage` in the MagazineArticle model
