### ISSUE TITLE
Upgrade to Bootstrap 5

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#367]
We are still using Bootstrap 4. Bootstrap 5 has some significant improvements.

## Task
- [ ] check any project dependencies for Bootstrap 5 compatibility
- [ ] upgrade to Bootstrap 5
- [ ] change any template semantics to use new Bootstrap 5 classes, etc.
