### ISSUE TITLE
Refactor import process related to magazine authors to use Postgres

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#503]
We are currently using SQLite in local development environment. This is mostly alright, although we are not able to use an advance query operator that would let us filter on sub-fields  of a set of Wagtail model types. The result is that our import logic relies on importing CSV files and performing in-memory look ups using pandas and numpy. Rather than using pandas, it would be more practical and forward-looking to use the database directly. This might also resolve some ambiguous import bugs we are facing related to article authors.

## Task

- [ ] update data models for de-duping Drupal article authors (e.g., by adding a list field for duplicate author IDs from a primary record)
- [ ] update the article authors import script to correctly identify the primary record and annotate it with duplicate IDs
- [x] update related import scripts to make database queries when cross-referencing authors rather than pandas (e.g. any calls to `.iloc` should use DB queries, and we shouldn't need to keep the authors table in memory)

## Resources

The following support request contains a comment describing how to search/filter Page sub-models based on custom fields:

- https://github.com/wagtail/wagtail/issues/5413

I opened a support request on StackOverflow
- https://stackoverflow.com/questions/75266918/wagtail-page-model-transitive-search-on-custom-fields
