### ISSUE TITLE
Create command to `scaffold_initial_nav_menu`

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#535]
Now that we have narrowed down our desired menu structure for the new site, we can create a command to quickly scaffold the desired menu structure. This will be useful for development and staging, as well as potentially for the final deployment.

## Task

- create a command to `scaffold_initial_nav_menu`
- make sure command creates desired menu structure currently fond in Sandbox

## Required pages

Ensure the following required pages exist in the `scaffold_initial_content` script.

- [x] MagazineIndexPage
- [x] DeepArchiveIndexPage
- [x] Future Issues(WFPage)
- [x] StoreIndexPage
- [x] LibraryIndexPage
- [ ] NewsletterIndexPage ?
- [ ] PodcastIndexPage ?
- [x] MemorialIndexPage
- [x] OnlineWorshipIndexPage
- [x] EventsIndexPage
- [x] Mission & History (WFPage)
- [x] Boad of Directors (WFPage)
- [x] CommunityDirectoryIndexPage
- [x] ContactFormPage
- [x] SubscriptionIndexPage
- [ ] NewsletterSubscriptionFormPage ?
- [x] DonatePage
- [x] Help Wanted (WFPage)

## Menu structure

- [x] Magazine / Books
     - [x] Recent Issues -> `MagazineIndexPage`
     - [x] Deep Archive -> `DeepArchiveIndexPage`
     - [x] Future Issues -> `WFPage` 
     - [x] Books -> `StoreIndexPage`
- [ ] Other Content
     - [x] Library / Media -> `LibraryIndexPage`
     - [ ] Newsletters -> NewsletterIndexPage ?
     - [ ] Podcasts -> PodcastIndexPage ?
     - [x] Memorials -> `MemorialIndexPage`
- [ ] Events
     - [x] Online Worship -> `OnlineWorshipIndexPage`
     - [x] Western Events -> `EventsIndexPage` (no querystring)
     - [ ] Other Events -> `EventsIndexPage` (querystring `category="other"`)
- [x] About Us
     - [x] Mission & History -> `WFPage`
     - [x] Board of Directors -> `WFPage`
     - [x] Directories -> `CommunityDirectoryIndexPage`
     - [x] Contact Us -> `ContactFormPage`
- [ ] Subscribe / Donate 
     - [x] Subscribe - Magazine -> `SubscriptionIndexPage`
     - [ ] Subscribe - Newsletter -> `NewsletterSubscriptionFormPage` ?
     - [x] Donate -> `DonatePage`
     - [x] Help Wanted -> `WFPage`

**Comment by brylie** [comment]
I've split the remaining items into a new issue so I can merge the current work.
