### ISSUE TITLE
Create Newsletter Signup page/feature

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#539]
Our sandbox site structure includes a "Subscribe - Newsletter" page that we want to replicate in this project.

## Task

- [ ] determine if we want to use Mailchimp directly for newsletter signups
- [ ] if so, figure out the best way to embed the Mailchimp sign up form
- [ ] otherwise, determine a workflow using Wagtail forms and manually copying sign up data to Mailchimp

## Resources

- Mailchimp: [Add an Embedded Signup Form to Your Website](https://mailchimp.com/help/add-a-signup-form-to-your-website/)

**Comment by brylie** [comment]
@marycklein, are we still planning on using Mailchimp to distribute the Western Friend newsletter? 

If so, we probably want to use an embedded Mailchimp sign-up form so the sign-ups flow to Mailchimp automatically. Conversely, if we use a Wagtail Form , we will need a process to manually copy the information to the correct Mailchimp list including when the recipients [consented to receiving the mailing list](https://mailchimp.com/gdpr/).

**Comment by brylie** [comment]
Alternatively, we can link directly to this sign-up page in the navigation menu: https://westernfriend.us4.list-manage.com/subscribe?u=0f903ecd7fe40d2cc1c8380a3&id=d3975648f3

**Comment by marycklein** [comment]
We should talk about this. I’m not 100% committed to mailchimp. I chose a different platform for the Palo Alto newsletter. This question goes beyond minimum viable I think.
!!
m

**Comment by brylie** [comment]
Yep, let's add it to our agenda at the next weekly meeting. While the Mailchimp decision may be beyond MVP, I want to understand where to point the "Subscribe - Newsletter" link in the sandbox navigation menu.

**Comment by brylie** [comment]
Closing this since I've added a placeholder "Subscribe - Newsletter" page to our site and navigation menu.
