### ISSUE TITLE
Determine best strategy for importing WF Page collection(s)

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#542]
There are several page collections defined on the existing Drupal website. This meta-issue tracks the work to manage the page collections individually or as generic WFPage entities in the new website.

## Collections

- [ ] 1041 Extra Extra items -> news #540 
- [ ] 45 Molly Wingate Blog items #434 
- [ ] 67 Online Worship items -> `OnlineWorship` collection https://github.com/WesternFriend/WF-website/issues/570
- [ ] 42 Public Board Doc items https://github.com/WesternFriend/WF-website/issues/569
- [ ] 123 YM Doc items #541 
- [ ] 78 generic pages -> WFPage (mostly or all?)

**Comment by brylie** [comment]
Molly Wingate Blog will be own sub-tree with top-level IndexPage that displays children sorted in reverse-chronological order.

**Comment by brylie** [comment]
We added a `topic` field to the Drupal Page model, so `WFPage` model may also need a `topics` many-to-many relationship. See #549

**Comment by brylie** [comment]
We may also want to use tags on pages. #550

**Comment by marycklein** [comment]
Re: Molly Wingate pages -- Since a "topic" field was available (when I went in and reset the "authored on" dates of the Drupal pages to match Molly's original dates), I went ahead and chose 1-3 "topics" for each child page

**Comment by marycklein** [comment]
I'm going to go through the "meta" list here and comment on each area.

**1. extra extra -** I believe we have decided to organize these to rely on essentially the same sets of "genre" and "topic" terms that we are using for faceted search in "media library" (though for "extra extra," we would say "type" rather then "genre" for news items). 

> Going forward in Wagtail, I will enter "event" news items as "events," and I will enter all other items as "news items."  This is assuming we can sort "events" into "western events" and "other events"

> The actual "news items" will either be a subset of items in the "media library" (one yes/no filter in library that asks: do these go in the "periodicals" section of the library, or instead "on the shelves"?) or, alternately, they could continue to be their own distinct category of content on the website.

> Also excellent would be to allow (but not require) items to be associated with monthly meetings and/or yearly meetings and/or individuals. New items should NOT require "authors" per se, since I am generally simply forwarding news items that other people have forwarded to me. I generally do not know the original authors of these news items.

**2. Molly Wingate Blog** -- I think we have this figured out.

**3. Online worship ** -- I would like to continue to provide a page where these opportunities are listed by time of week and time of day when they occur. Like this: https://westernfriend.org/quaker-worship-and-fellowship-online

**4. Public Board Documents** -- 

> I would like to continue sorting these by categories like so: https://westernfriend.org/public-board-documents

> We also have a collection of "board member only" documents here: https://westernfriend.org/board-documents 
Many of those links go to pages in our NextCloud.

**5. Yearly Meeting Documents** -- I would like to continue sorting these by categories and years, like so: https://westernfriend.org/annual-sessions-photos-and-epistles

**6. Generic Pages** -- is there some way to generate a list of URLs for these pages so that I can go through them and think about what we need to do with them?

**Comment by brylie** [comment]
Since the scope of changes mentioned above is relatively large and each section of the website has different nuances, I've split this task into the following issues where we can continue with more focused work and discussion:

- https://github.com/WesternFriend/WF-website/issues/571
- https://github.com/WesternFriend/WF-website/issues/570
- https://github.com/WesternFriend/WF-website/issues/569
- https://github.com/WesternFriend/WF-website/issues/541

**Comment by brylie** [comment]
Closing this, since we have sub-issues for each page type/collection
