### ISSUE TITLE
Add and configure django-stubs package

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#700]
We have recently been adding type annotations through the project and using `mypy` to help us write safer code. However, there are many `mypy` errors related to Django internals, such as model defintions.

There is a package called [django-stubs](https://github.com/typeddjango/django-stubs) that adds correct type annotation for Django internals.

## Task

- [ ] add the [django-stubs](https://github.com/typeddjango/django-stubs) package as a project dependency
- [ ] follow the configuration instructions in the django-stubs project README
- [ ] ensure the mypy errors are resolved
