### ISSUE TITLE
Use correct float when importing images

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#735]
We currently default all imported images to being left aligned. However, some images are right-aligned via `float: right` in the existing website content.

In the import script, while handling image tags, try to check for a style attribute containing a `float` rule. Use that rule to select whether the image should be left or right-aligned.

## Task
- [x] add help text
- [x] allow `None` value for `float`, default to `None`
- [x] allowed `float` values: `left` and `right` or any valid CSS float value
- [x] in template: if float is not None add style attribute with `float: {{ image.float }}` (or equivalent)
- [x] update import script to use the new float attribute (check the previous float value from the `img.style` attribute when importing and assign it to the new `image.float` property
