### ISSUE TITLE
Include CKEditor CSS rules in the site base template

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#737]
The current website allows content to be indented via the WYSIWYG editor. To display the indented content, the website adds a `rteindent1` class with the following CSS rules from the `ckeditor.css`:

```css
/* General indentation & positioning classes */

.rteindent1 {
    margin-left: 40px;
}
.rteindent2 {
    margin-left: 80px;
}
.rteindent3 {
    margin-left: 120px;
}
.rteindent4 {
    margin-left: 160px;
}
.rteleft {
    text-align: left;
}
.rteright {
    text-align: right;
}
.rtecenter {
    text-align: center;
}
.rtejustify {
    text-align: justify;
}
.ibimage_left {
    float: left;
}
.ibimage_right {
    float: right;
}
```

Let's include those rules in our CSS file to preserve backward compatibility with CKEditor content formatting applied by the editor.

## Task

- [ ] create a new file `common/static/ckeditor.css`
- [ ] add the above CSS rules to the file
- [ ] include the CSS rules in our base template `base.html`
