### ISSUE TITLE
Prioritize Faith and Practice books in Bookstore display

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#823]
Split from #793

@marycklein asks

Can we display the three Fath and Practice books first, then diplay all the rest in alpha order by title?

## Task

- [ ] add a `featured` boolean field to the `Book` model
- [ ] update the [products_index_page.html template](https://github.com/WesternFriend/WF-website/blob/main/store/templates/store/store_index_page.html) as follows
    - [ ] one Bootstrap row rendering a grid of featured books
    - [ ] a second row rendering a grid of non-featured books (so there are no repeated books)

Note: use the existing markup by duplicating it. The only thing that needs to change is the querysets. There will need to be two querysets. Alternatively, use the [Django regroup template tag](https://docs.djangoproject.com/en/4.2/ref/templates/builtins/#regroup) to regroup by featured true/false.

**Comment by brylie** [comment]
We can probably add a "featured" checkmark that will feature selected books alphabetically at the top of the list. The remaining, "unfeatured" books will come afterwords in alphabetical order.

E.g.

<featured>
- IMYM F&P
- NPYM F&O
- PacYM F&P
<the rest>
- A book
- B book
- C book

**Comment by ErnstBas** [comment]
Hi @brylie I hope this finds you well. Can I help with this issue?
Can I also point out a problem? I have set up the development environment again for this project. When running the server locally I noticed that the Wagtail CMS does not display correctly the workspace and also the website itself does not display images or any other content (despite adding the basic content). Is something missing, or is it me?

**Comment by brylie** [comment]
Thanks @ErnstBas. I'll assign you.

Create a `.env` file containing `DJANGO?DEBUG=true` so things like CSS will load in the development environment. This has been updated in the contributing guide under the [Application Configuration section](https://github.com/WesternFriend/WF-website/blob/main/docs/CONTRIBUTING.md#application-configuration).

**Comment by ErnstBas** [comment]
Hi @brylie I could need some advice. I added a boolean field is_featured to models.py and with the dictsortreversed filter in store_index_page.html the featured and non featured books can be grouped. The problem is, I do manage to display the grouped books in an alphabetical order. I have some difficulty understanding which variable stores the book title. Could you point me in the right direction?
Do you want me to add a views.py file to order the books, or do you prefer the ordering to take place only in the file store_index_page.html?
