### ISSUE TITLE
Handle all relevant Braintree webhooks

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#899]
We currently have a Braintree webhook endpoint that doesn't do much, if anything. We would like to handle Braintree webhooks, such as cancel subscription and subscription renewal success.

## Task

- [ ] determine appropriate Braintree webhooks to handle in WesternFriend website
- [ ] implement logic in our local webhook handler to respond correctly to webhooks
- [ ] make sure to update any relevant entities in the database to reflect the result of the webhook, such as extending the subscription validity period for renewals

## References

- https://developer.paypal.com/braintree/docs/guides/webhooks/overview
